import type {Citizen} from "./types.ts";

export const citizens: Citizen[] = [
    {
        id: 'C-000001',
        firstName: 'Иван',
        lastName: 'Петров',
        middleName: 'Иванович',
        birthDate: '1990-02-12',
        gender: 'male',
        citizenship: 'Российская Федерация',
        phone: '+7 (910) 423-55-55',
        email: 'iv.petrov@example.com',
        region: 'Москва',
        city: 'Москва',
        address: 'Арбатская улица, 33, кв. 22',
        inn: '771234467830',
        snils: '422-554-999 00',
        status: 'active',

        family: [
            {
                id: 'D-002',
                fullName: 'Петрова Мария Андреевна',
                relationship: 'Супруга',
                birthDate: '1988-04-12',
            },
            {
                id: 'H-003',
                fullName: 'Петров Алексей Иванович',
                relationship: 'Сын',
                birthDate: '2015-03-22',
            },
        ],
        education: [
            {
                id: 'E-001',
                institution: 'Московский государственный университет',
                degree: 'Высшее',
                graduationYear: 2010,
                specialty: 'Экономика',
            },
        ],
        documents: [
            {
                id: 'D-001',
                type: 'passport',
                number: '4512 123456',
                issueDate: '2019-05-12',
                status: 'active',
            },
        ],
    },

    {
        id: 'C-000002',
        firstName: 'Анна',
        lastName: 'Смирнова',
        middleName: 'Сергеевна',
        birthDate: '1992-07-18',
        gender: 'female',
        citizenship: 'Российская Федерация',
        phone: '+7 (921) 555-12-34',
        email: 'anna.smirnova@example.com',
        region: 'Санкт-Петербург',
        city: 'Санкт-Петербург',
        address: 'Невский проспект, 45, кв. 18',
        inn: '781234567890',
        snils: '123-456-789 01',
        status: 'active',

        family: [
            {
                id: 'H-004',
                fullName: 'Смирнов Дмитрий Алексеевич',
                relationship: 'Супруг',
                birthDate: '1990-11-03',
            },
        ],
        education: [
            {
                id: 'E-002',
                institution: 'Санкт-Петербургский государственный университет',
                degree: 'Высшее',
                graduationYear: 2014,
                specialty: 'Юриспруденция',
            },
        ],
        documents: [
            {
                id: 'D-003',
                type: 'passport',
                number: '4011 654321',
                issueDate: '2022-08-20',
                status: 'active',
            },
        ],
    },

    {
        id: 'C-000003',
        firstName: 'Александр',
        lastName: 'Соколов',
        middleName: 'Дмитриевич',
        birthDate: '1985-02-09',
        gender: 'male',
        citizenship: 'Российская Федерация',
        phone: '+7 (903) 777-45-67',
        email: 'alex.sokolov@example.com',
        region: 'Московская область',
        city: 'Химки',
        address: 'Ленинградская улица, 12, кв. 45',
        inn: '504712345678',
        snils: '234-567-890 12',
        status: 'verification',

        family: [
            {
                id: 'D-004',
                fullName: 'Соколова Елена Викторовна',
                relationship: 'Супруга',
                birthDate: '1987-06-25',
            },
            {
                id: 'H-005',
                fullName: 'Соколов Максим Александрович',
                relationship: 'Сын',
                birthDate: '2012-09-14',
            },
        ],
        education: [
            {
                id: 'E-003',
                institution: 'Национальный исследовательский университет',
                degree: 'Высшее',
                graduationYear: 2008,
                specialty: 'Информационные технологии',
            },
        ],
        documents: [
            {
                id: 'D-005',
                type: 'passport',
                number: '4610 987654',
                issueDate: '2020-03-15',
                status: 'active',
            },
        ],
    },

    {
        id: 'C-000004',
        firstName: 'Екатерина',
        lastName: 'Волкова',
        middleName: 'Александровна',
        birthDate: '1995-11-24',
        gender: 'female',
        citizenship: 'Российская Федерация',
        phone: '+7 (916) 234-78-91',
        email: 'ek.volkova@example.com',
        region: 'Москва',
        city: 'Москва',
        address: 'Тверская улица, 18, кв. 41',
        inn: '770412345678',
        snils: '345-678-901 23',
        status: 'active',

        family: [
            {
                id: 'H-006',
                fullName: 'Волков Артем Сергеевич',
                relationship: 'Супруг',
                birthDate: '1993-08-17',
            },
        ],
        education: [
            {
                id: 'E-004',
                institution: 'Российский экономический университет',
                degree: 'Высшее',
                graduationYear: 2017,
                specialty: 'Финансы и кредит',
            },
        ],
        documents: [
            {
                id: 'D-006',
                type: 'passport',
                number: '4509 234567',
                issueDate: '2021-06-18',
                status: 'active',
            },
        ],
    },

    {
        id: 'C-000005',
        firstName: 'Дмитрий',
        lastName: 'Кузнецов',
        middleName: 'Олегович',
        birthDate: '1989-05-16',
        gender: 'male',
        citizenship: 'Российская Федерация',
        phone: '+7 (985) 345-67-12',
        email: 'd.kuznetsov@example.com',
        region: 'Московская область',
        city: 'Мытищи',
        address: 'Олимпийский проспект, 27, кв. 16',
        inn: '502912345678',
        snils: '456-789-012 34',
        status: 'blocked',

        family: [
            {
                id: 'D-007',
                fullName: 'Кузнецова Ольга Павловна',
                relationship: 'Супруга',
                birthDate: '1991-10-03',
            },
            {
                id: 'H-008',
                fullName: 'Кузнецов Никита Дмитриевич',
                relationship: 'Сын',
                birthDate: '2018-07-11',
            },
        ],
        education: [
            {
                id: 'E-005',
                institution: 'Московский технический университет',
                degree: 'Высшее',
                graduationYear: 2012,
                specialty: 'Информатика',
            },
        ],
        documents: [
            {
                id: 'D-008',
                type: 'passport',
                number: '4608 345678',
                issueDate: '2019-11-22',
                status: 'active',
            },
        ],
    },

    {
        id: 'C-000006',
        firstName: 'Марина',
        lastName: 'Попова',
        middleName: 'Игоревна',
        birthDate: '1993-03-08',
        gender: 'female',
        citizenship: 'Российская Федерация',
        phone: '+7 (999) 456-23-45',
        email: 'marina.popova@example.com',
        region: 'Свердловская область',
        city: 'Екатеринбург',
        address: 'Малышева улица, 72, кв. 35',
        inn: '667112345678',
        snils: '567-890-123 45',
        status: 'verification',

        family: [],
        education: [
            {
                id: 'E-006',
                institution: 'Уральский федеральный университет',
                degree: 'Высшее',
                graduationYear: 2015,
                specialty: 'Менеджмент',
            },
        ],
        documents: [
            {
                id: 'D-009',
                type: 'passport',
                number: '6507 456789',
                issueDate: '2020-09-14',
                status: 'active',
            },
        ],
    },

    {
        id: 'C-000007',
        firstName: 'Сергей',
        lastName: 'Морозов',
        middleName: 'Андреевич',
        birthDate: '1982-12-19',
        gender: 'male',
        citizenship: 'Российская Федерация',
        phone: '+7 (903) 567-89-01',
        email: 's.morozov@example.com',
        region: 'Республика Татарстан',
        city: 'Казань',
        address: 'Баумана улица, 15, кв. 28',
        inn: '165012345678',
        snils: '678-901-234 56',
        status: 'active',

        family: [
            {
                id: 'D-010',
                fullName: 'Морозова Наталья Викторовна',
                relationship: 'Супруга',
                birthDate: '1985-04-21',
            },
        ],
        education: [
            {
                id: 'E-007',
                institution: 'Казанский федеральный университет',
                degree: 'Высшее',
                graduationYear: 2005,
                specialty: 'Юриспруденция',
            },
        ],
        documents: [
            {
                id: 'D-011',
                type: 'passport',
                number: '9211 567890',
                issueDate: '2018-04-27',
                status: 'active',
            },
        ],
    },

    {
        id: 'C-000008',
        firstName: 'Ольга',
        lastName: 'Лебедева',
        middleName: 'Владимировна',
        birthDate: '1990-08-27',
        gender: 'female',
        citizenship: 'Российская Федерация',
        phone: '+7 (912) 678-12-34',
        email: 'o.lebedeva@example.com',
        region: 'Новосибирская область',
        city: 'Новосибирск',
        address: 'Красный проспект, 102, кв. 54',
        inn: '540612345678',
        snils: '789-012-345 67',
        status: 'active',

        family: [
            {
                id: 'H-012',
                fullName: 'Лебедев Михаил Олегович',
                relationship: 'Сын',
                birthDate: '2016-05-19',
            },
        ],
        education: [
            {
                id: 'E-008',
                institution: 'Новосибирский государственный университет',
                degree: 'Высшее',
                graduationYear: 2013,
                specialty: 'Математика',
            },
        ],
        documents: [
            {
                id: 'D-013',
                type: 'passport',
                number: '5406 678901',
                issueDate: '2020-12-10',
                status: 'active',
            },
        ],
    },

    {
        id: 'C-000009',
        firstName: 'Михаил',
        lastName: 'Федоров',
        middleName: 'Петрович',
        birthDate: '1978-06-14',
        gender: 'male',
        citizenship: 'Российская Федерация',
        phone: '+7 (905) 781-23-45',
        email: 'm.fedorov@example.com',
        region: 'Самарская область',
        city: 'Самара',
        address: 'Московское шоссе, 31, кв. 72',
        inn: '631212345678',
        snils: '890-123-456 78',
        status: 'active',
        family: [
            {
                id: 'D-014',
                fullName: 'Федорова Ирина Сергеевна',
                relationship: 'Супруга',
                birthDate: '1980-09-27',
            },
            {
                id: 'H-015',
                fullName: 'Федоров Кирилл Михайлович',
                relationship: 'Сын',
                birthDate: '2010-02-15',
            },
            {
                id: 'H-016',
                fullName: 'Федорова Алиса Михайловна',
                relationship: 'Дочь',
                birthDate: '2014-11-09',
            },
        ],
        education: [
            {
                id: 'E-009',
                institution: 'Самарский государственный технический университет',
                degree: 'Высшее',
                graduationYear: 2001,
                specialty: 'Машиностроение',
            },
        ],
        documents: [
            {
                id: 'D-017',
                type: 'passport',
                number: '6304 789012',
                issueDate: '2017-02-11',
                status: 'active',
            },
        ],
    },

    {
        id: 'C-000010',
        firstName: 'Наталья',
        lastName: 'Орлова',
        middleName: 'Викторовна',
        birthDate: '1987-10-05',
        gender: 'female',
        citizenship: 'Российская Федерация',
        phone: '+7 (917) 812-34-56',
        email: 'n.orlova@example.com',
        region: 'Республика Башкортостан',
        city: 'Уфа',
        address: 'Ленина улица, 56, кв. 19',
        inn: '027412345678',
        snils: '901-234-567 89',
        status: 'verification',
        family: [],
        education: [
            {
                id: 'E-010',
                institution: 'Башкирский государственный университет',
                degree: 'Высшее',
                graduationYear: 2009,
                specialty: 'Педагогика',
            },
        ],
        documents: [
            {
                id: 'D-018',
                type: 'passport',
                number: '8009 890123',
                issueDate: '2021-01-23',
                status: 'active',
            },
        ],
    },

    {
        id: 'C-000011',
        firstName: 'Артем',
        lastName: 'Захаров',
        middleName: 'Ильич',
        birthDate: '1996-01-28',
        gender: 'male',
        citizenship: 'Российская Федерация',
        phone: '+7 (926) 923-45-67',
        email: 'a.zakharov@example.com',
        region: 'Москва',
        city: 'Москва',
        address: 'Профсоюзная улица, 89, кв. 31',
        inn: '772812345678',
        snils: '012-345-678 90',
        status: 'active',
        family: [],
        education: [
            {
                id: 'E-011',
                institution: 'Московский политехнический университет',
                degree: 'Высшее',
                graduationYear: 2018,
                specialty: 'Программная инженерия',
            },
        ],
        documents: [
            {
                id: 'D-019',
                type: 'passport',
                number: '4516 901234',
                issueDate: '2022-02-17',
                status: 'active',
            },
        ],
    },

    {
        id: 'C-000012',
        firstName: 'Татьяна',
        lastName: 'Макарова',
        middleName: 'Алексеевна',
        birthDate: '1984-04-17',
        gender: 'female',
        citizenship: 'Российская Федерация',
        phone: '+7 (911) 134-56-78',
        email: 't.makarova@example.com',
        region: 'Ленинградская область',
        city: 'Всеволожск',
        address: 'Октябрьский проспект, 44, кв. 12',
        inn: '470312345678',
        snils: '112-345-678 90',
        status: 'blocked',
        family: [
            {
                id: 'H-020',
                fullName: 'Макаров Денис Александрович',
                relationship: 'Сын',
                birthDate: '2011-08-23',
            },
        ],
        education: [
            {
                id: 'E-012',
                institution: 'Санкт-Петербургский университет экономики',
                degree: 'Высшее',
                graduationYear: 2006,
                specialty: 'Бухгалтерский учет',
            },
        ],
        documents: [
            {
                id: 'D-021',
                type: 'passport',
                number: '4015 012345',
                issueDate: '2019-07-08',
                status: 'active',
            },
        ],
    },

    {
        id: 'C-000013',
        firstName: 'Роман',
        lastName: 'Никитин',
        middleName: 'Валерьевич',
        birthDate: '1991-09-12',
        gender: 'male',
        citizenship: 'Российская Федерация',
        phone: '+7 (916) 245-67-89',
        email: 'r.nikitin@example.com',
        region: 'Воронежская область',
        city: 'Воронеж',
        address: 'Плехановская улица, 25, кв. 47',
        inn: '366212345678',
        snils: '223-456-789 01',
        status: 'active',
        family: [
            {
                id: 'D-022',
                fullName: 'Никитина Светлана Олеговна',
                relationship: 'Супруга',
                birthDate: '1993-12-04',
            },
        ],
        education: [
            {
                id: 'E-013',
                institution: 'Воронежский государственный университет',
                degree: 'Высшее',
                graduationYear: 2013,
                specialty: 'Физика',
            },
        ],
        documents: [
            {
                id: 'D-023',
                type: 'passport',
                number: '3620 123456',
                issueDate: '2020-05-19',
                status: 'active',
            },
        ],
    },

    {
        id: 'C-000014',
        firstName: 'Светлана',
        lastName: 'Алексеева',
        middleName: 'Романовна',
        birthDate: '1998-12-03',
        gender: 'female',
        citizenship: 'Российская Федерация',
        phone: '+7 (952) 356-78-90',
        email: 's.alexeeva@example.com',
        region: 'Краснодарский край',
        city: 'Краснодар',
        address: 'Красная улица, 76, кв. 21',
        inn: '231112345678',
        snils: '334-567-890 12',
        status: 'active',
        family: [],
        education: [
            {
                id: 'E-014',
                institution: 'Кубанский государственный университет',
                degree: 'Высшее',
                graduationYear: 2020,
                specialty: 'Маркетинг',
            },
        ],
        documents: [
            {
                id: 'D-024',
                type: 'passport',
                number: '0318 234567',
                issueDate: '2021-11-30',
                status: 'active',
            },
        ],
    },

    {
        id: 'C-000015',
        firstName: 'Владимир',
        lastName: 'Григорьев',
        middleName: 'Михайлович',
        birthDate: '1975-07-22',
        gender: 'male',
        citizenship: 'Российская Федерация',
        phone: '+7 (903) 467-89-01',
        email: 'v.grigoriev@example.com',
        region: 'Ростовская область',
        city: 'Ростов-на-Дону',
        address: 'Большая Садовая улица, 118, кв. 64',
        inn: '616412345678',
        snils: '445-678-901 23',
        status: 'verification',
        family: [
            {
                id: 'D-025',
                fullName: 'Григорьева Людмила Ивановна',
                relationship: 'Супруга',
                birthDate: '1978-03-16',
            },
        ],
        education: [
            {
                id: 'E-015',
                institution: 'Южный федеральный университет',
                degree: 'Высшее',
                graduationYear: 1997,
                specialty: 'История',
            },
        ],
        documents: [
            {
                id: 'D-026',
                type: 'passport',
                number: '6012 345678',
                issueDate: '2016-10-04',
                status: 'active',
            },
        ],
    },

    {
        id: 'C-000016',
        firstName: 'Юлия',
        lastName: 'Романова',
        middleName: 'Игоревна',
        birthDate: '1994-05-29',
        gender: 'female',
        citizenship: 'Российская Федерация',
        phone: '+7 (977) 578-90-12',
        email: 'y.romanova@example.com',
        region: 'Нижегородская область',
        city: 'Нижний Новгород',
        address: 'Большая Покровская улица, 39, кв. 15',
        inn: '526012345678',
        snils: '556-789-012 34',
        status: 'active',
        family: [
            {
                id: 'H-027',
                fullName: 'Романов Павел Дмитриевич',
                relationship: 'Сын',
                birthDate: '2020-01-14',
            },
        ],
        education: [
            {
                id: 'E-016',
                institution: 'Нижегородский государственный университет',
                degree: 'Высшее',
                graduationYear: 2016,
                specialty: 'Филология',
            },
        ],
        documents: [
            {
                id: 'D-028',
                type: 'passport',
                number: '5209 456789',
                issueDate: '2022-04-16',
                status: 'active',
            },
        ],
    },

    {
        id: 'C-000017',
        firstName: 'Константин',
        lastName: 'Белов',
        middleName: 'Сергеевич',
        birthDate: '1988-11-11',
        gender: 'male',
        citizenship: 'Российская Федерация',
        phone: '+7 (905) 689-01-23',
        email: 'k.belov@example.com',
        region: 'Пермский край',
        city: 'Пермь',
        address: 'Комсомольский проспект, 54, кв. 36',
        inn: '590312345678',
        snils: '667-890-123 45',
        status: 'active',
        family: [],
        education: [
            {
                id: 'E-017',
                institution: 'Пермский государственный университет',
                degree: 'Высшее',
                graduationYear: 2011,
                specialty: 'Инженерное дело',
            },
        ],
        documents: [
            {
                id: 'D-029',
                type: 'passport',
                number: '5908 567890',
                issueDate: '2019-09-21',
                status: 'active',
            },
        ],
    },

    {
        id: 'C-000018',
        firstName: 'Ирина',
        lastName: 'Крылова',
        middleName: 'Максимовна',
        birthDate: '1991-01-07',
        gender: 'female',
        citizenship: 'Российская Федерация',
        phone: '+7 (913) 790-12-34',
        email: 'i.krylova@example.com',
        region: 'Омская область',
        city: 'Омск',
        address: 'Ленина улица, 88, кв. 27',
        inn: '550412345678',
        snils: '778-901-234 56',
        status: 'blocked',
        family: [
            {
                id: 'H-030',
                fullName: 'Крылов Матвей Сергеевич',
                relationship: 'Сын',
                birthDate: '2017-06-30',
            },
        ],
        education: [
            {
                id: 'E-018',
                institution: 'Омский государственный университет',
                degree: 'Высшее',
                graduationYear: 2012,
                specialty: 'Социология',
            },
        ],
        documents: [
            {
                id: 'D-031',
                type: 'passport',
                number: '5203 678901',
                issueDate: '2020-02-12',
                status: 'active',
            },
        ],
    },

    {
        id: 'C-000019',
        firstName: 'Максим',
        lastName: 'Виноградов',
        middleName: 'Александрович',
        birthDate: '1986-09-18',
        gender: 'male',
        citizenship: 'Российская Федерация',
        phone: '+7 (916) 801-23-45',
        email: 'm.vinogradov@example.com',
        region: 'Тульская область',
        city: 'Тула',
        address: 'Советская улица, 42, кв. 18',
        inn: '710312345678',
        snils: '889-012-345 67',
        status: 'active',
        family: [
            {
                id: 'D-032',
                fullName: 'Виноградова Анна Николаевна',
                relationship: 'Супруга',
                birthDate: '1988-02-26',
            },
            {
                id: 'H-033',
                fullName: 'Виноградов Арсений Максимович',
                relationship: 'Сын',
                birthDate: '2014-04-08',
            },
        ],
        education: [
            {
                id: 'E-019',
                institution: 'Тульский государственный университет',
                degree: 'Высшее',
                graduationYear: 2009,
                specialty: 'Механика',
            },
        ],
        documents: [
            {
                id: 'D-034',
                type: 'passport',
                number: '7106 789012',
                issueDate: '2018-12-03',
                status: 'active',
            },
        ],
    },

    {
        id: 'C-000020',
        firstName: 'Анастасия',
        lastName: 'Зайцева',
        middleName: 'Денисовна',
        birthDate: '1997-03-15',
        gender: 'female',
        citizenship: 'Российская Федерация',
        phone: '+7 (929) 912-34-56',
        email: 'a.zaitseva@example.com',
        region: 'Красноярский край',
        city: 'Красноярск',
        address: 'Карла Маркса улица, 63, кв. 44',
        inn: '240712345678',
        snils: '990-123-456 78',
        status: 'verification',
        family: [],
        education: [
            {
                id: 'E-020',
                institution: 'Сибирский федеральный университет',
                degree: 'Высшее',
                graduationYear: 2019,
                specialty: 'Дизайн',
            },
        ],
        documents: [
            {
                id: 'D-035',
                type: 'passport',
                number: '2409 890123',
                issueDate: '2021-08-14',
                status: 'active',
            },
        ],
    },

    {
        id: 'C-000021',
        firstName: 'Николай',
        lastName: 'Тарасов',
        middleName: 'Викторович',
        birthDate: '1981-04-23',
        gender: 'male',
        citizenship: 'Российская Федерация',
        phone: '+7 (913) 123-45-67',
        email: 'n.tarasov@example.com',
        region: 'Тюменская область',
        city: 'Тюмень',
        address: 'Республики улица, 101, кв. 57',
        inn: '720312345678',
        snils: '101-234-567 89',
        status: 'active',
        family: [
            {
                id: 'D-036',
                fullName: 'Тарасова Елена Михайловна',
                relationship: 'Супруга',
                birthDate: '1983-07-12',
            },
            {
                id: 'H-037',
                fullName: 'Тарасов Иван Николаевич',
                relationship: 'Сын',
                birthDate: '2009-10-21',
            },
        ],
        education: [
            {
                id: 'E-021',
                institution: 'Тюменский государственный университет',
                degree: 'Высшее',
                graduationYear: 2003,
                specialty: 'Нефтегазовое дело',
            },
        ],
        documents: [
            {
                id: 'D-038',
                type: 'passport',
                number: '7205 901234',
                issueDate: '2017-06-15',
                status: 'active',
            },
        ],
    },

    {
        id: 'C-000022',
        firstName: 'Виктория',
        lastName: 'Семенова',
        middleName: 'Андреевна',
        birthDate: '1996-08-09',
        gender: 'female',
        citizenship: 'Российская Федерация',
        phone: '+7 (981) 234-56-78',
        email: 'v.semenova@example.com',
        region: 'Санкт-Петербург',
        city: 'Санкт-Петербург',
        address: 'Московский проспект, 88, кв. 19',
        inn: '781612345678',
        snils: '212-345-678 90',
        status: 'active',
        family: [],
        education: [
            {
                id: 'E-022',
                institution: 'Санкт-Петербургский политехнический университет',
                degree: 'Высшее',
                graduationYear: 2018,
                specialty: 'Прикладная математика',
            },
        ],
        documents: [
            {
                id: 'D-039',
                type: 'passport',
                number: '4017 012345',
                issueDate: '2022-01-09',
                status: 'active',
            },
        ],
    },

    {
        id: 'C-000023',
        firstName: 'Евгений',
        lastName: 'Мельников',
        middleName: 'Романович',
        birthDate: '1983-12-28',
        gender: 'male',
        citizenship: 'Российская Федерация',
        phone: '+7 (905) 345-67-89',
        email: 'e.melnikov@example.com',
        region: 'Челябинская область',
        city: 'Челябинск',
        address: 'Комсомольский проспект, 77, кв. 52',
        inn: '744812345678',
        snils: '323-456-789 01',
        status: 'blocked',
        family: [
            {
                id: 'D-040',
                fullName: 'Мельникова Оксана Игоревна',
                relationship: 'Супруга',
                birthDate: '1986-05-17',
            },
        ],
        education: [
            {
                id: 'E-023',
                institution: 'Южно-Уральский государственный университет',
                degree: 'Высшее',
                graduationYear: 2005,
                specialty: 'Энергетика',
            },
        ],
        documents: [
            {
                id: 'D-041',
                type: 'passport',
                number: '7504 123456',
                issueDate: '2018-03-28',
                status: 'active',
            },
        ],
    },

    {
        id: 'C-000024',
        firstName: 'Дарья',
        lastName: 'Комарова',
        middleName: 'Ильинична',
        birthDate: '1999-10-31',
        gender: 'female',
        citizenship: 'Российская Федерация',
        phone: '+7 (952) 456-78-90',
        email: 'd.komarova@example.com',
        region: 'Волгоградская область',
        city: 'Волгоград',
        address: 'Мира улица, 14, кв. 8',
        inn: '344412345678',
        snils: '434-567-890 12',
        status: 'verification',
        family: [],
        education: [
            {
                id: 'E-024',
                institution: 'Волгоградский государственный университет',
                degree: 'Высшее',
                graduationYear: 2021,
                specialty: 'Экономика',
            },
        ],
        documents: [
            {
                id: 'D-042',
                type: 'passport',
                number: '3408 234567',
                issueDate: '2022-12-01',
                status: 'active',
            },
        ],
    },

    {
        id: 'C-000025',
        firstName: 'Павел',
        lastName: 'Королев',
        middleName: 'Владимирович',
        birthDate: '1990-06-06',
        gender: 'male',
        citizenship: 'Российская Федерация',
        phone: '+7 (916) 567-89-01',
        email: 'p.korolev@example.com',
        region: 'Московская область',
        city: 'Подольск',
        address: 'Кирова улица, 35, кв. 26',
        inn: '503612345678',
        snils: '545-678-901 23',
        status: 'active',
        family: [
            {
                id: 'D-043',
                fullName: 'Королева Марина Сергеевна',
                relationship: 'Супруга',
                birthDate: '1992-01-18',
            },
            {
                id: 'H-044',
                fullName: 'Королев Тимофей Павлович',
                relationship: 'Сын',
                birthDate: '2019-09-05',
            },
        ],
        education: [
            {
                id: 'E-025',
                institution: 'Московский авиационный институт',
                degree: 'Высшее',
                graduationYear: 2012,
                specialty: 'Автоматизация',
            },
        ],
        documents: [
            {
                id: 'D-045',
                type: 'passport',
                number: '4607 345678',
                issueDate: '2019-10-16',
                status: 'active',
            },
        ],
    },

    {
        id: 'C-000026',
        firstName: 'Ксения',
        lastName: 'Николаева',
        middleName: 'Павловна',
        birthDate: '1993-02-21',
        gender: 'female',
        citizenship: 'Российская Федерация',
        phone: '+7 (999) 678-90-12',
        email: 'k.nikolaeva@example.com',
        region: 'Ярославская область',
        city: 'Ярославль',
        address: 'Свободы улица, 28, кв. 33',
        inn: '760412345678',
        snils: '656-789-012 34',
        status: 'active',
        family: [],
        education: [
            {
                id: 'E-026',
                institution: 'Ярославский государственный университет',
                degree: 'Высшее',
                graduationYear: 2015,
                specialty: 'Психология',
            },
        ],
        documents: [
            {
                id: 'D-046',
                type: 'passport',
                number: '7606 456789',
                issueDate: '2020-06-22',
                status: 'active',
            },
        ],
    },

    {
        id: 'C-000027',
        firstName: 'Георгий',
        lastName: 'Данилов',
        middleName: 'Аркадьевич',
        birthDate: '1979-11-26',
        gender: 'male',
        citizenship: 'Российская Федерация',
        phone: '+7 (903) 789-01-23',
        email: 'g.danilov@example.com',
        region: 'Саратовская область',
        city: 'Саратов',
        address: 'Московская улица, 61, кв. 45',
        inn: '645012345678',
        snils: '767-890-123 45',
        status: 'active',
        family: [
            {
                id: 'D-047',
                fullName: 'Данилова Татьяна Викторовна',
                relationship: 'Супруга',
                birthDate: '1981-05-09',
            },
            {
                id: 'H-048',
                fullName: 'Данилов Артем Георгиевич',
                relationship: 'Сын',
                birthDate: '2008-12-17',
            },
            {
                id: 'H-049',
                fullName: 'Данилова Полина Георгиевна',
                relationship: 'Дочь',
                birthDate: '2013-07-25',
            },
        ],
        education: [
            {
                id: 'E-027',
                institution: 'Саратовский государственный университет',
                degree: 'Высшее',
                graduationYear: 2001,
                specialty: 'История',
            },
        ],
        documents: [
            {
                id: 'D-050',
                type: 'passport',
                number: '6303 567890',
                issueDate: '2016-11-18',
                status: 'active',
            },
        ],
    },

    {
        id: 'C-000028',
        firstName: 'Полина',
        lastName: 'Баранова',
        middleName: 'Евгеньевна',
        birthDate: '1995-07-13',
        gender: 'female',
        citizenship: 'Российская Федерация',
        phone: '+7 (921) 890-12-34',
        email: 'p.baranova@example.com',
        region: 'Калининградская область',
        city: 'Калининград',
        address: 'Ленинский проспект, 9, кв. 17',
        inn: '390612345678',
        snils: '878-901-234 56',
        status: 'verification',
        family: [],
        education: [
            {
                id: 'E-028',
                institution: 'Балтийский федеральный университет',
                degree: 'Высшее',
                graduationYear: 2017,
                specialty: 'Иностранные языки',
            },
        ],
        documents: [
            {
                id: 'D-051',
                type: 'passport',
                number: '3908 678901',
                issueDate: '2021-03-27',
                status: 'active',
            },
        ],
    },

    {
        id: 'C-000029',
        firstName: 'Игорь',
        lastName: 'Ершов',
        middleName: 'Константинович',
        birthDate: '1987-03-30',
        gender: 'male',
        citizenship: 'Российская Федерация',
        phone: '+7 (915) 901-23-45',
        email: 'i.ershov@example.com',
        region: 'Тверская область',
        city: 'Тверь',
        address: 'Советская улица, 19, кв. 37',
        inn: '690612345678',
        snils: '989-012-345 67',
        status: 'blocked',
        family: [
            {
                id: 'D-052',
                fullName: 'Ершова Екатерина Максимовна',
                relationship: 'Супруга',
                birthDate: '1989-08-14',
            },
        ],
        education: [
            {
                id: 'E-029',
                institution: 'Тверской государственный университет',
                degree: 'Высшее',
                graduationYear: 2009,
                specialty: 'Физическая культура',
            },
        ],
        documents: [
            {
                id: 'D-053',
                type: 'passport',
                number: '6907 789012',
                issueDate: '2018-08-11',
                status: 'active',
            },
        ],
    },

    {
        id: 'C-000030',
        firstName: 'Алина',
        lastName: 'Фролова',
        middleName: 'Владиславовна',
        birthDate: '2000-09-17',
        gender: 'female',
        citizenship: 'Российская Федерация',
        phone: '+7 (999) 012-34-56',
        email: 'a.frolova@example.com',
        region: 'Приморский край',
        city: 'Владивосток',
        address: 'Светланская улица, 81, кв. 23',
        inn: '253612345678',
        snils: '090-123-456 78',
        status: 'active',
        family: [],
        education: [
            {
                id: 'E-030',
                institution: 'Дальневосточный федеральный университет',
                degree: 'Высшее',
                graduationYear: 2022,
                specialty: 'Информационные технологии',
            },
        ],
        documents: [
            {
                id: 'D-054',
                type: 'passport',
                number: '2509 890123',
                issueDate: '2022-10-14',
                status: 'active',
            },
        ],
    },


];